const careers=[['✦','Astronomía','Explorá el universo, estudiá los astros y descubrí los secretos del cosmos.'],['〰','Geofísica','Entendé la Tierra, sus procesos y los fenómenos que la transforman.'],['☁','Meteorología','Analizá el tiempo, el clima y su impacto en nuestro planeta.']];
const features=[['⌂','La Facultad'],['◉','El Observatorio'],['◌','Planetario'],['◎','Gran Ecuatorial'],['⚗','Investigación'],['♧','Vida universitaria']];
const activities=[['12 ABR','Charla en escuela','La Plata','Astronomía'],['18 ABR','Charla virtual','Buenos Aires','Geofísica'],['25 ABR','Feria educativa','Mar del Plata','Meteorología']];
export default function Home(){return <><header><div className="logo">📚 <span>Estudiá<br/><b>ciencia</b><small>ESTUDIÁ EN EL OBSER</small></span></div><nav><a href="#inicio">Inicio</a><a href="#carreras">Carreras</a><a href="#obser">Estudiar en el Obser</a><a href="#actividades">Actividades</a><a href="#escuelas">Para escuelas</a><a href="#preguntas">Preguntas</a></nav><a className="pill" href="#escuelas">Quiero conocer más →</a></header>
<section id="inicio" className="hero"><div className="stars"/><div className="copy"><small>ESTUDIÁ CIENCIA · ESTUDIÁ EN EL OBSER</small><h1>¿Y si tu futuro está entre las <i>estrellas,</i><strong> bajo nuestros pies</strong> o en el cielo?</h1><p>Conocé <b>Astronomía, Geofísica y Meteorología</b> y descubrí qué podés hacer estudiando en el Obser.</p><div><a className="btn" href="#carreras">Conocé las carreras →</a><a className="btn ghost" href="#actividades">Ver actividades</a></div></div><div className="dome"><span/></div></section>
<section id="carreras" className="section"><div className="heading"><div><small>LAS 3 CARRERAS</small><h2>Tres formas de mirar el mundo</h2></div><p>Astronomía, Geofísica y Meteorología.<br/>Tres disciplinas, un mismo lugar: la FCAG-UNLP.</p></div><div className="cards">{careers.map((c,i)=><article className={'career c'+i} key={c[1]}><div className="photo">{c[0]}</div><div><h3>{c[1]}</h3><p>{c[2]}</p><a href="#obser">Ver más →</a></div></article>)}</div></section>
<section id="obser" className="section white"><div className="heading"><div><small>EL LUGAR</small><h2>¿Por qué estudiar<br/>en el Obser?</h2></div><p>La Facultad de Ciencias Astronómicas y Geofísicas de la UNLP es un lugar único para aprender, investigar y crecer.</p></div><div className="features">{features.map(f=><div key={f[1]}><span>{f[0]}</span><h3>{f[1]}</h3><p>Conocé una parte de la experiencia universitaria.</p></div>)}</div></section>
<section id="escuelas" className="school"><div className="schoolpic"><b>¿Querés que<br/>vayamos a tu<br/>escuela?</b></div><div><small>PARA ESCUELAS</small><h2>Llevamos la ciencia<br/>a tu institución</h2><p>Charlas, talleres y actividades virtuales o presenciales para estudiantes del nivel secundario.</p><a className="btn dark" href="mailto:estudia-ciencia@fcaglp.unlp.edu.ar">Solicitá una visita →</a><aside><span>⌖ <b>Presencial</b><small>La Plata y alrededores</small></span><span>▣ <b>Virtual</b><small>Interior de la Provincia de Buenos Aires y otras provincias</small></span></aside></div></section>
<section id="actividades" className="section"><div className="heading"><div><small>PRÓXIMAS ACTIVIDADES</small><h2>¡Sumate!</h2></div><p>Charlas, visitas, ferias y mucho más. Conocé las actividades y viví la ciencia de cerca.</p></div><div className="activities">{activities.map(a=><article key={a[0]}><div className="activitypic">✦</div><small>▣ {a[0]}</small><h3>{a[1]}</h3><p>⌖ {a[2]}</p><p>✦ {a[3]} <b>→</b></p></article>)}</div></section>
<section id="preguntas" className="questions"><small>NO HAY PREGUNTAS TONTAS</small><h2>¿Tenés dudas sobre las carreras?</h2><p>Estamos para ayudarte a elegir tu próximo camino.</p><a className="btn" href="#carreras">Quiero saber más →</a></section>
<footer><div className="footerlogo">📚 <b>Estudiá<br/>ciencia</b><small>ESTUDIÁ EN EL OBSER</small></div><div>Inicio　 Carreras　 Estudiar en el Obser　 Actividades　 Para escuelas　 Preguntas</div><em>La ciencia también se estudia.</em></footer></>}
